# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: echo.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import service as _service
from google.protobuf import service_reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)




DESCRIPTOR = _descriptor.FileDescriptor(
  name='echo.proto',
  package='transport.hrpc.example.echo',
  serialized_pb='\n\necho.proto\x12\x1btransport.hrpc.example.echo\"\x16\n\x07Request\x12\x0b\n\x03msg\x18\x01 \x02(\t\"\x17\n\x08Response\x12\x0b\n\x03msg\x18\x01 \x02(\t2b\n\x0b\x45\x63hoService\x12S\n\x04\x65\x63ho\x12$.transport.hrpc.example.echo.Request\x1a%.transport.hrpc.example.echo.ResponseB\x03\x90\x01\x01')




_REQUEST = _descriptor.Descriptor(
  name='Request',
  full_name='transport.hrpc.example.echo.Request',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='msg', full_name='transport.hrpc.example.echo.Request.msg', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=43,
  serialized_end=65,
)


_RESPONSE = _descriptor.Descriptor(
  name='Response',
  full_name='transport.hrpc.example.echo.Response',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='msg', full_name='transport.hrpc.example.echo.Response.msg', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=67,
  serialized_end=90,
)

DESCRIPTOR.message_types_by_name['Request'] = _REQUEST
DESCRIPTOR.message_types_by_name['Response'] = _RESPONSE

class Request(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _REQUEST

  # @@protoc_insertion_point(class_scope:transport.hrpc.example.echo.Request)

class Response(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _RESPONSE

  # @@protoc_insertion_point(class_scope:transport.hrpc.example.echo.Response)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), '\220\001\001')

_ECHOSERVICE = _descriptor.ServiceDescriptor(
  name='EchoService',
  full_name='transport.hrpc.example.echo.EchoService',
  file=DESCRIPTOR,
  index=0,
  options=None,
  serialized_start=92,
  serialized_end=190,
  methods=[
  _descriptor.MethodDescriptor(
    name='echo',
    full_name='transport.hrpc.example.echo.EchoService.echo',
    index=0,
    containing_service=None,
    input_type=_REQUEST,
    output_type=_RESPONSE,
    options=None,
  ),
])

class EchoService(_service.Service):
  __metaclass__ = service_reflection.GeneratedServiceType
  DESCRIPTOR = _ECHOSERVICE
class EchoService_Stub(EchoService):
  __metaclass__ = service_reflection.GeneratedServiceStubType
  DESCRIPTOR = _ECHOSERVICE

# @@protoc_insertion_point(module_scope)
