# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: service.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import service as _service
from google.protobuf import service_reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)


import message_pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='service.proto',
  package='service',
  serialized_pb='\n\rservice.proto\x12\x07service\x1a\rmessage.proto2G\n\x07Service\x12<\n\x07get_msg\x12\x17.message.MessageRequest\x1a\x18.message.MessageResponseB\x03\x90\x01\x01')





DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), '\220\001\001')

_SERVICE = _descriptor.ServiceDescriptor(
  name='Service',
  full_name='service.Service',
  file=DESCRIPTOR,
  index=0,
  options=None,
  serialized_start=41,
  serialized_end=112,
  methods=[
  _descriptor.MethodDescriptor(
    name='get_msg',
    full_name='service.Service.get_msg',
    index=0,
    containing_service=None,
    input_type=message_pb2._MESSAGEREQUEST,
    output_type=message_pb2._MESSAGERESPONSE,
    options=None,
  ),
])

class Service(_service.Service):
  __metaclass__ = service_reflection.GeneratedServiceType
  DESCRIPTOR = _SERVICE
class Service_Stub(Service):
  __metaclass__ = service_reflection.GeneratedServiceStubType
  DESCRIPTOR = _SERVICE

# @@protoc_insertion_point(module_scope)
